name: optiserve
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - networkx=3.3
  - numpy=1.26.4
  - pandas=2.2.2
  - scikit-learn=1.5.0
  - boto3=1.34.127
  - python-dotenv=1.0.1
  - tqdm=4.66.4
  - requests=2.32.3
  - seaborn=0.13.2
  - pip
  - pip:
      - matplotlib==3.9.0
      - sagemaker==2.224.4
